#!/bin/bash
# shellcheck disable=SC2154 # Lifecycle globals come from the sourced lifecycle module.
# OmaSecBoot: status display and file verification

list_limine_unhashed_paths() {
  local config
  config=$(limine_config_path)
  [[ -f "$config" ]] || return 0

  awk '
    function normalise_protocol(value) {
      value = tolower(value)
      if (value == "uefi" || value == "efi_chainload") return "efi"
      if (value == "bios_chainload") return "bios"
      return value
    }

    function trim(value) {
      sub(/^[[:space:]]+/, "", value)
      sub(/[[:space:]]+$/, "", value)
      return value
    }
    function has_hash(value) {
      return value ~ /#[0-9A-Fa-f]{128}([[:space:]]|$)/
    }
    function reset_entry() {
      protocol = ""
      path_count = 0
    }
    function remember_path(key, value, line_no) {
      if (!has_hash(value)) {
        path_count++
        path_lines[path_count] = line_no ": " key ": " value
      }
    }
    function flush_entry(    i) {
      if (protocol == "efi" || protocol == "efi_boot_entry") {
        reset_entry()
        return
      }
      for (i = 1; i <= path_count; i++) {
        print path_lines[i]
      }
      reset_entry()
    }
    BEGIN {
      path_key["path"] = 1
      path_key["kernel_path"] = 1
      path_key["module_path"] = 1
      path_key["image_path"] = 1
      path_key["dtb_path"] = 1
      reset_entry()
    }
    /^[[:space:]]*#/ || /^[[:space:]]*$/ { next }
    {
      line = trim($0)
      # Limine strips leading whitespace, so entry lines ("/Name", "//Sub")
      # generated by limine-entry-tool/limine-snapper-sync may be indented.
      if (line ~ /^\//) { flush_entry(); next }
      colon = index(line, ":")
      if (colon == 0) next

      key = tolower(substr(line, 1, colon - 1))
      value = trim(substr(line, colon + 1))

      if (key == "protocol") {
        protocol = normalise_protocol(value)
        next
      }

      if (key == "global_dtb") {
        if (!has_hash(value)) print NR ": " key ": " value
        next
      }

      if (!(key in path_key)) next
      remember_path(key, value, NR)
    }
    END { flush_entry() }
  ' "$config"
}

list_limine_v12_color_warnings() {
  local config
  config=$(limine_config_path)
  [[ -f "$config" ]] || return 0

  awk '
    function trim(value) {
      sub(/^[[:space:]]+/, "", value)
      sub(/[[:space:]]+$/, "", value)
      return value
    }
    BEGIN {
      color_key["interface_branding_color"] = 1
      color_key["interface_branding_colour"] = 1
      color_key["interface_help_color"] = 1
      color_key["interface_help_colour"] = 1
      color_key["interface_help_color_bright"] = 1
      color_key["interface_help_colour_bright"] = 1
    }
    /^[[:space:]]*#/ || /^[[:space:]]*$/ { next }
    {
      line = trim($0)
      colon = index(line, ":")
      if (colon == 0) next

      key = tolower(substr(line, 1, colon - 1))
      value = trim(substr(line, colon + 1))

      if ((key in color_key) && value !~ /^[0-9A-Fa-f]{6}$/) {
        print NR ": " key ": " value
      }
    }
  ' "$config"
}

list_unmanaged_windows_chainloads() {
  local config
  config=$(limine_config_path)
  [[ -f "$config" ]] || return 0

  awk '
    function normalise_protocol(value) {
      value = tolower(value)
      if (value == "uefi" || value == "efi_chainload") return "efi"
      return value
    }

    function trim(value) {
      sub(/^[[:space:]]+/, "", value)
      sub(/[[:space:]]+$/, "", value)
      return value
    }
    /^[[:space:]]*#/ || /^[[:space:]]*$/ { next }
    {
      line = trim($0)
      # Limine strips leading whitespace, so entry lines ("/Name", "//Sub")
      # generated by limine-entry-tool/limine-snapper-sync may be indented.
      if (line ~ /^\//) { in_windows = (tolower(line) ~ /windows/); next }
      if (!in_windows) next
      colon = index(line, ":")
      if (colon == 0) next

      key = tolower(substr(line, 1, colon - 1))
      value = normalise_protocol(trim(substr(line, colon + 1)))
      if (key == "protocol" && value == "efi") {
        print NR ": " line
      }
    }
  ' "$config"
}

list_windows_firmware_entries() {
  command -v efibootmgr >/dev/null 2>&1 || return 0
  efibootmgr -v 2>/dev/null | grep -i 'bootmgfw\.efi' || true
}

list_omarchy_direct_boot_entries() {
  command -v efibootmgr >/dev/null 2>&1 || return 0
  efibootmgr -v 2>/dev/null | grep -Ei '^Boot[0-9A-Fa-f]+\*?[[:space:]]+Omarchy.*\\EFI\\Linux\\omarchy.*\.efi' || true
}

show_lifecycle_status() {
  if ! read_lifecycle; then
    fail "Lifecycle state is invalid or unsafe"
    return 1
  fi
  case "$_lifecycle_state" in
    unmanaged)
      warn "Lifecycle: unmanaged (explicit setup or adoption required)"
      return 1
      ;;
    disabled) pass "Lifecycle: disabled" ;;
    active) pass "Lifecycle: active" ;;
    transition)
      if [[ "$EUID" == "$(control_owner_uid)" ]]; then
        if ! read_transaction_manifest "$_lifecycle_transaction_id"; then
          fail "Lifecycle: recovery-required (invalid transaction ${_lifecycle_transaction_id})"
          return 1
        fi
        if ! manifest_owner_is_alive; then
          fail "Lifecycle: recovery-required (stale transaction ${_lifecycle_transaction_id})"
          return 1
        fi
      fi
      warn "Lifecycle: transition (${_lifecycle_transaction_id})"
      return 1
      ;;
    recovery-required)
      fail "Lifecycle: recovery-required (${_lifecycle_transaction_id})"
      return 1
      ;;
    *)
      fail "Lifecycle: unsupported state"
      return 1
      ;;
  esac
}

# Firmware and key state from one sbctl status document; prints the raw status
# when the document is unavailable.
show_firmware_status() {
  local json="$1" ok=true installed_state setup_mode_state secure_boot_state vendors
  if [[ -z "$json" || "$json" == "null" ]]; then
    sbctl status
    echo
    return 0
  fi
  read -r installed_state setup_mode_state secure_boot_state < <(
    jq -r '[.installed, .setup_mode, .secure_boot] | map(. // false) | @tsv' <<< "$json"
  )
  vendors=$(jq -r '
    .vendors // [] | if type == "array" then
      map(tostring) | sort | unique | join(", ")
    else
      tostring
    end
  ' <<< "$json")
  if [[ "$installed_state" == "true" ]]; then
    pass "sbctl keys installed"
  else
    fail "sbctl keys not installed"
    ok=false
  fi
  if [[ "$secure_boot_state" == "true" ]]; then
    pass "Secure Boot enabled"
  else
    fail "Secure Boot disabled"
    ok=false
  fi
  if [[ "$setup_mode_state" == "true" ]]; then
    warn "Setup Mode active"
  else
    pass "Setup Mode disabled"
  fi
  [[ -n "$vendors" && "$vendors" != "null" ]] && echo -e "  ${DIM}Vendor keys: ${vendors}${NC}"
  [[ "$ok" == true ]]
}

# The pacman hook sbctl ships for re-signing after upgrades.
sbctl_resign_hook_path() {
  printf '/usr/share/libalpm/hooks/zz-sbctl.hook\n'
}

# Locations a pre-package source install left behind.
stale_source_install_paths() {
  printf '%s\n' /usr/local/bin/omasecboot /usr/local/lib/omasecboot
}

# Installed hooks by canonical content and executing command target, HookDir
# shadowing, and stale source installs. A missing hook fails only while the
# lifecycle is active; a present hook that does not validate fails in every
# state, because activation would refuse it.
show_hook_status() {
  local ok=true entry key hook_label hook_path command hook_name shadow_dir path
  command=$(current_omasecboot_executable_path) || command=""
  for entry in "removal|dependency removal guard" "transaction|transaction guard" \
    "package-sign|post-sbctl lifecycle checkpoint" \
    "limine-pre|Limine pre-mutation guard" "limine-post|Limine post-mutation checkpoint"; do
    key=${entry%%|*}
    hook_label=${entry#*|}
    hook_path=$(activation_hook_path "$key") || { ok=false; continue; }
    if [[ ! -f "$hook_path" ]]; then
      warn "${hook_path##*/} missing; install the packaged OmaSecBoot release before activation"
      [[ ${_lifecycle_state:-unmanaged} != active ]] || ok=false
    elif [[ -n "$command" ]] && validate_activation_hook "$key" "$command"; then
      pass "${hook_path##*/} present (${hook_label})"
    else
      fail "${hook_path##*/} is not the packaged hook or targets another command; reinstall the package"
      ok=false
    fi
  done
  hook_path=$(sbctl_resign_hook_path)
  if [[ -f "$hook_path" ]]; then
    pass "${hook_path##*/} present (re-signing)"
  else
    warn "${hook_path##*/} missing. Run: ${BOLD}sudo pacman -S sbctl${NC}"
    [[ ${_lifecycle_state:-unmanaged} != active ]] || ok=false
  fi
  for hook_name in 00-omasecboot-removal-guard.hook 00-omasecboot-transition-guard.hook \
    zzz-omasecboot.hook; do
    if pacman_hook_is_shadowed "$(pacman_system_hook_dir)/${hook_name}"; then
      shadow_dir=$(pacman_configured_hook_dirs 2>/dev/null | tr '\n' ' ')
      fail "${hook_name} is shadowed by a same-named hook in a configured HookDir (${shadow_dir% }); remove the stale copy"
      ok=false
    fi
  done
  while IFS= read -r path; do
    [[ -e "$path" ]] || continue
    fail "Stale source install at ${path}; remove it and its hooks before activation"
    ok=false
    break
  done < <(stale_source_install_paths)
  [[ "$ok" == true ]]
}

# limine-snapper-sync.service state; advisory only.
show_service_status() {
  command -v systemctl >/dev/null 2>&1 || return 0
  local load_state enabled_state active_state
  load_state=$(systemctl show -p LoadState --value limine-snapper-sync.service 2>/dev/null || true)
  [[ "$load_state" == "loaded" ]] || return 0
  enabled_state=$(systemctl is-enabled limine-snapper-sync.service 2>/dev/null || true)
  active_state=$(systemctl is-active limine-snapper-sync.service 2>/dev/null || true)
  if [[ "$enabled_state" == "enabled" ]]; then
    pass "limine-snapper-sync.service enabled"
  else
    warn "limine-snapper-sync.service not enabled (${enabled_state:-unknown})"
  fi
  if [[ "$active_state" == "active" ]]; then
    pass "limine-snapper-sync.service active"
  else
    warn "limine-snapper-sync.service not active (${active_state:-unknown})"
    if ! command -v inotifywait >/dev/null 2>&1; then
      echo -e "  ${DIM}limine-snapper-sync's optional file watcher requires ${BOLD}inotify-tools${NC}${DIM} (not needed by this repo's Limine post-hook)${NC}"
    fi
  fi
}

show_esp_status() {
  if ! { command -v mountpoint && command -v findmnt; } >/dev/null 2>&1; then
    warn "mountpoint/findmnt unavailable; cannot verify $(esp_path) mount"
    return 0
  fi
  if esp_is_mounted_vfat; then
    pass "$(esp_path) mounted as vfat"
  else
    fail "$(esp_path) is not mounted as the FAT32 ESP"
    return 1
  fi
}

# The managed /etc/default/limine settings, the enrollment hooks, and Limine 12
# path-hash readiness.
show_limine_config_status() {
  local secure_boot_state="$1" ok=true line
  if [[ ! -f "$(limine_default_config_path)" ]]; then
    fail "$(limine_default_config_path) not found"
    return 1
  fi
  local enable_verification enable_enroll before_save after_save
  enable_verification=$(limine_managed_setting_state ENABLE_VERIFICATION 2>/dev/null) \
    || enable_verification=invalid
  if [[ "$enable_verification" == no ]]; then
    pass "ENABLE_VERIFICATION=no"
  else
    fail "ENABLE_VERIFICATION is not one clean no (${enable_verification})"
    ok=false
  fi
  enable_enroll=$(limine_managed_setting_state ENABLE_ENROLL_LIMINE_CONFIG 2>/dev/null) \
    || enable_enroll=invalid
  if [[ "$enable_enroll" == yes ]]; then
    pass "ENABLE_ENROLL_LIMINE_CONFIG=yes"
  else
    fail "ENABLE_ENROLL_LIMINE_CONFIG is not one clean yes (${enable_enroll})"
    ok=false
  fi
  before_save=$(limine_managed_token_state COMMANDS_BEFORE_SAVE limine-reset-enroll \
    2>/dev/null) || before_save=invalid
  after_save=$(limine_managed_token_state COMMANDS_AFTER_SAVE limine-enroll-config \
    2>/dev/null) || after_save=invalid
  if limine_enrollment_hooks_present; then
    pass "Limine enrollment hooks present"
    if [[ "$before_save" != absent || "$after_save" != absent ]]; then
      warn "deprecated COMMANDS_* enrollment entries remain; run sudo omasecboot sign to remove them safely"
    fi
  else
    warn "Limine enrollment hooks missing; checking deprecated COMMANDS_* fallback"
    if [[ "$before_save" == present ]]; then
      pass "COMMANDS_BEFORE_SAVE includes limine-reset-enroll"
    else
      fail "COMMANDS_BEFORE_SAVE is missing limine-reset-enroll fallback"
      ok=false
    fi
    if [[ "$after_save" == present ]]; then
      pass "COMMANDS_AFTER_SAVE includes limine-enroll-config"
    else
      fail "COMMANDS_AFTER_SAVE is missing limine-enroll-config fallback"
      ok=false
    fi
  fi

  local limine_major="" limine_ver=""
  limine_ver=$(limine_version 2>/dev/null || true)
  limine_major=$(limine_major_version 2>/dev/null || true)
  if [[ -n "$limine_ver" ]]; then
    pass "Limine ${limine_ver} installed"
  fi

  local color_warnings unhashed_paths limine_v12_or_newer=false
  if [[ -n "$limine_major" && $limine_major -ge 12 ]]; then
    limine_v12_or_newer=true
  fi
  color_warnings=$(list_limine_v12_color_warnings)
  if [[ -n "$color_warnings" ]]; then
    warn "Limine 12 expects interface colors as RRGGBB values"
    while IFS= read -r line; do
      echo -e "    ${YELLOW}!${NC} $(limine_config_path):${line}"
    done <<< "$color_warnings"
  fi
  if [[ "$enable_enroll" != "yes" ]]; then
    echo -e "  ${DIM}Limine 12 path-hash enforcement inactive unless config enrollment is active${NC}"
    [[ "$ok" == true ]]
    return $?
  fi
  unhashed_paths=$(list_limine_unhashed_paths) || unhashed_paths=""
  if [[ -z "$unhashed_paths" ]]; then
    pass "Limine 12 path-hash readiness passed for non-EFI loaded paths"
  elif [[ "$limine_v12_or_newer" == true && "$secure_boot_state" == "true" ]]; then
    fail "Limine 12 Secure Boot path-hash enforcement may block boot"
    while IFS= read -r line; do
      echo -e "    ${RED}✗${NC} $(limine_config_path):${line}"
    done <<< "$unhashed_paths"
    ok=false
  else
    warn "Limine 12 readiness: non-EFI loaded paths are missing BLAKE2B hashes"
    while IFS= read -r line; do
      echo -e "    ${YELLOW}!${NC} $(limine_config_path):${line}"
    done <<< "$unhashed_paths"
  fi
  [[ "$ok" == true ]]
}

# Shadowing config candidates on the ESP and the enrolled checksum proof.
show_limine_checksum_status() {
  local shadow_config shadow_config_found=false current_config_checksum scope
  while IFS= read -r shadow_config; do
    if [[ -e "$shadow_config" || -L "$shadow_config" ]]; then
      fail "Possible Limine config shadowing file: ${shadow_config}"
      shadow_config_found=true
    fi
  done < <(limine_shadow_config_paths)
  if ! limine_fallback_policy >/dev/null; then
    fail "ENABLE_LIMINE_FALLBACK could not be resolved from the limine-entry-tool configuration"
    return 1
  fi
  if limine_fallback_is_managed; then
    scope="both boot binaries"
  else
    scope="the primary boot binary (fallback loader not deployed, ENABLE_LIMINE_FALLBACK=no)"
  fi
  if [[ "$shadow_config_found" == false ]] \
    && current_config_checksum=$(current_limine_config_checksum) \
    && verify_limine_config_targets "$current_config_checksum"; then
    pass "Current Limine config checksum enrolled in ${scope}"
    return 0
  fi
  [[ "$shadow_config_found" == true ]] \
    || fail "Current Limine config checksum is not proved in ${scope}"
  return 1
}

# Firmware boot entries and the managed Windows handoff.
show_windows_status() {
  local ok=true line direct_boot_entries
  direct_boot_entries=$(list_omarchy_direct_boot_entries)
  if [[ -n "$direct_boot_entries" ]]; then
    warn "Omarchy Direct Boot firmware entry enabled"
    while IFS= read -r line; do
      echo -e "    ${YELLOW}!${NC} ${line}"
    done <<< "$direct_boot_entries"
    echo -e "  ${DIM}Direct Boot bypasses the Limine menu, including snapshots and repo-managed Windows entries.${NC}"
  fi

  local windows_boot_entries windows_boot_count windows_target windows_target_rc=0
  local target_number target_label
  windows_target=$(find_windows_boot_entry 2>/dev/null) || windows_target_rc=$?
  windows_boot_entries=$(list_windows_firmware_entries)
  windows_boot_count=$(grep -c . <<< "$windows_boot_entries") || windows_boot_count=0
  if [[ $windows_target_rc -eq 0 && -n "$windows_target" ]]; then
    pass "Unique active Windows firmware handoff target"
  elif [[ $windows_boot_count -gt 0 ]]; then
    warn "Windows firmware entries do not resolve to one safe handoff target"
    while IFS= read -r line; do
      echo -e "    ${YELLOW}!${NC} ${line}"
    done <<< "$windows_boot_entries"
    ok=false
  else
    echo -e "  ${DIM}No Windows Boot Manager found (check BIOS boot settings)${NC}"
  fi

  local windows_state_file
  local _windows_error _windows_block_state _windows_state_kind
  local _windows_block_start _windows_block_count
  local _windows_state_boot_number _windows_state_label
  local _windows_state_partuuid _windows_state_loader_path
  windows_state_file=$(windows_target_state_path)
  if read_windows_target_state; then
    pass "Durable Windows firmware target identity recorded"
    IFS=$'\t' read -r target_number target_label <<< "$windows_target"
    if [[ $windows_target_rc -eq 0 ]] \
      && [[ "$_windows_state_boot_number" != "$target_number" \
        || "$_windows_state_label" != "$target_label" ]]; then
      fail "Recorded Windows target Boot${_windows_state_boot_number} is not the firmware target Boot${target_number}; run sudo omasecboot windows setup again"
      ok=false
    fi
    if windows_managed_block_state "$_windows_state_label"; then
      case "$_windows_block_state" in
        canonical)
          pass "Windows boot entry in limine.conf (firmware BootNext)"
          ;;
        legacy)
          warn "Managed Windows entry uses the legacy unbounded marker"
          ok=false
          ;;
        absent)
          warn "Durable Windows opt-in is recorded but its managed entry is suppressed"
          ok=false
          ;;
        *)
          fail "Managed Windows entry state is invalid"
          ok=false
          ;;
      esac
    else
      warn "Managed Windows entry in limine.conf is malformed or mismatched"
      ok=false
    fi
  elif [[ -e "$windows_state_file" || -L "$windows_state_file" ]]; then
    if windows_classify_target_state && [[ "$_windows_state_kind" == legacy-empty ]]; then
      warn "Legacy Windows opt-in marker needs explicit target migration"
    else
      fail "Durable Windows target state is invalid or unsafe"
    fi
    ok=false
  elif grep -Fq "$WINDOWS_ENTRY_MARKER" "$(limine_config_path)" 2>/dev/null \
    || grep -Fq "$WINDOWS_ENTRY_END_MARKER" "$(limine_config_path)" 2>/dev/null \
    || grep -Fq "$WINDOWS_LEGACY_ENTRY_MARKER" "$(limine_config_path)" 2>/dev/null; then
    warn "Managed Windows entry has no durable target identity"
    ok=false
  else
    echo -e "  ${DIM}No managed Windows firmware handoff configured${NC}"
  fi

  local unmanaged_windows_chainloads
  unmanaged_windows_chainloads=$(list_unmanaged_windows_chainloads)
  if [[ -n "$unmanaged_windows_chainloads" ]]; then
    warn "Windows EFI chainload entry may trigger BitLocker"
    while IFS= read -r line; do
      echo -e "    ${YELLOW}!${NC} $(limine_config_path):${line}"
    done <<< "$unmanaged_windows_chainloads"
    echo -e "  ${DIM}Omarchy Quattro's limine-scan creates this protocol: efi form.${NC}"
    echo -e "  ${DIM}OmaSecBoot uses firmware BootNext to keep Limine out of the Windows measurement chain.${NC}"
    echo -e "  ${DIM}Run sudo omasecboot windows setup to add the validated firmware handoff; remove the chainload entry from limine.conf yourself.${NC}"
  fi
  [[ "$ok" == true ]]
}

# Tracked-file verification, root only. The closing line reflects file state
# alone, not the other sections.
show_tracked_files_status() {
  if [[ "$EUID" != "$(control_owner_uid)" ]]; then
    echo
    echo -e "  ${DIM}Run as root for file verification: ${BOLD}sudo omasecboot status${NC}"
    return 0
  fi
  echo
  echo -e "  ${BOLD}Tracked Files${NC}"
  local ok=true file enrolled_raw enrolled_rc=0 stale_entries stale_rc=0
  local stale_file stale_output discovered_raw discovery_rc=0
  local -a enrolled=() discovered=() untracked=() missing_tracked=()
  local -A enrolled_map=()

  enrolled_raw=$(list_enrolled_paths) || enrolled_rc=$?
  stale_entries=$(list_stale_sbctl_entries) || stale_rc=$?
  discovered_raw=$(discover_efi_files) || discovery_rc=$?
  if [[ $discovery_rc -ne 0 ]]; then
    fail "Could not discover the EFI artifacts under $(esp_path)"
    ok=false
  elif [[ -n "$discovered_raw" ]]; then
    mapfile -t discovered <<< "$discovered_raw"
  fi

  if [[ $stale_rc -eq 0 && -n "$stale_entries" ]]; then
    while IFS=$'\t' read -r stale_file stale_output; do
      stale_output="${stale_output:-$stale_file}"
      if [[ ! -e "$stale_file" || ! -e "$stale_output" ]]; then
        if [[ "$stale_file" == "$stale_output" ]]; then
          missing_tracked+=("$stale_file")
        else
          missing_tracked+=("$stale_file -> $stale_output")
        fi
      fi
    done <<< "$stale_entries"
  fi

  if [[ $enrolled_rc -ne 0 ]]; then
    fail "Could not read sbctl tracking state"
    ok=false
  elif [[ -n "$enrolled_raw" ]]; then
    mapfile -t enrolled <<< "$enrolled_raw"
  fi

  if [[ $enrolled_rc -ne 0 ]]; then
    : # already reported above
  elif [[ ${#enrolled[@]} -eq 0 ]]; then
    warn "No files in sbctl database"
    [[ ${#discovered[@]} -eq 0 ]] || ok=false
  else
    for file in "${enrolled[@]}"; do
      enrolled_map["$file"]=1
    done
    for file in "${discovered[@]}"; do
      if [[ -z "${enrolled_map[$file]:-}" ]]; then
        untracked+=("$file")
      fi
    done
    for file in "${enrolled[@]}"; do
      if sbctl_file_signature_state "$file"; then
        echo -e "    ${GREEN}✓${NC} $file"
      else
        echo -e "    ${RED}✗${NC} $file"
        ok=false
      fi
    done
    if [[ ${#untracked[@]} -gt 0 ]]; then
      echo
      warn "Untracked EFI files found (${#untracked[@]})"
      for file in "${untracked[@]}"; do
        echo -e "    ${YELLOW}!${NC} $file"
      done
      if printf '%s\n' "${untracked[@]}" | grep -Eq '\.efi_(sha1|sha256|b3|blake3|xxh|xxhash)_'; then
        echo -e "  ${DIM}Snapshot UKIs exist outside sbctl's database. Run sudo omasecboot sign before rebooting.${NC}"
      fi
      ok=false
    fi
  fi

  if [[ $enrolled_rc -eq 0 && ${#missing_tracked[@]} -gt 0 ]]; then
    echo
    warn "Stale sbctl tracked files found"
    for stale_file in "${missing_tracked[@]}"; do
      echo -e "    ${YELLOW}!${NC} $stale_file"
    done
    echo -e "  ${DIM}Run sudo omasecboot cleanup to remove stale tracking safely.${NC}"
    ok=false
  fi

  if [[ $enrolled_rc -eq 0 && ${#enrolled[@]} -gt 0 ]]; then
    echo
    if [[ "$ok" == true ]]; then
      pass "All tracked files signed and all discovered EFI files enrolled"
    else
      warn "Some files failed. Run sudo omasecboot sign to repair and prove them"
    fi
  fi
  [[ "$ok" == true ]]
}

show_status() {
  header "Secure Boot Status"
  local all_ok=true json secure_boot_state
  json=$(sbctl status --json 2>/dev/null) || true
  show_firmware_status "$json" || all_ok=false
  secure_boot_state=$(jq -r '.secure_boot // false' <<< "$json" 2>/dev/null) \
    || secure_boot_state=false
  echo
  show_hook_status || all_ok=false
  show_service_status
  echo
  echo -e "  ${BOLD}ESP Mount${NC}"
  show_esp_status || all_ok=false
  echo
  echo -e "  ${BOLD}Limine Config${NC}"
  show_limine_config_status "$secure_boot_state" || all_ok=false
  show_limine_checksum_status || all_ok=false
  show_windows_status || all_ok=false
  show_tracked_files_status || all_ok=false
  echo
  [[ "$all_ok" == true ]]
}
