#!/bin/bash
# OmaSecBoot: status display and file verification

strip_outer_quotes() {
  local value="$1"
  if [[ "$value" == \"*\" && "$value" == *\" ]]; then
    value=${value:1:${#value}-2}
  fi
  printf '%s\n' "$value"
}

limine_default_has_command() {
  local value
  load_limine_default_entry "$1" || return 1
  value=$(strip_outer_quotes "${_limine_default_raw:-}") || return 1
  [[ " $value " == *" $2 "* ]]
}

list_limine_unhashed_paths() {
  [[ -f "$LIMINE_CONF" ]] || return 0

  awk '
    function normalise_protocol(value) {
      value = tolower(value)
      if (value == "uefi" || value == "efi_chainload") return "efi"
      if (value == "bios_chainload") return "bios"
      return value
    }

    function trim(value) {
      sub(/^[[:space:]]+/, "", value)
      sub(/[[:space:]]+$/, "", value)
      return value
    }
    function has_hash(value) {
      return value ~ /#[0-9A-Fa-f]{128}([[:space:]]|$)/
    }
    function reset_entry() {
      protocol = ""
      path_count = 0
    }
    function remember_path(key, value, line_no) {
      if (!has_hash(value)) {
        path_count++
        path_lines[path_count] = line_no ": " key ": " value
      }
    }
    function flush_entry(    i) {
      if (protocol == "efi" || protocol == "efi_boot_entry") {
        reset_entry()
        return
      }
      for (i = 1; i <= path_count; i++) {
        print path_lines[i]
      }
      reset_entry()
    }
    BEGIN {
      path_key["path"] = 1
      path_key["kernel_path"] = 1
      path_key["module_path"] = 1
      path_key["image_path"] = 1
      path_key["dtb_path"] = 1
      reset_entry()
    }
    /^[[:space:]]*#/ || /^[[:space:]]*$/ { next }
    {
      line = trim($0)
      # Limine strips leading whitespace, so entry lines ("/Name", "//Sub")
      # generated by limine-entry-tool/limine-snapper-sync may be indented.
      if (line ~ /^\//) { flush_entry(); next }
      colon = index(line, ":")
      if (colon == 0) next

      key = tolower(substr(line, 1, colon - 1))
      value = trim(substr(line, colon + 1))

      if (key == "protocol") {
        protocol = normalise_protocol(value)
        next
      }

      if (key == "global_dtb") {
        if (!has_hash(value)) print NR ": " key ": " value
        next
      }

      if (!(key in path_key)) next
      remember_path(key, value, NR)
    }
    END { flush_entry() }
  ' "$LIMINE_CONF"
}

list_limine_v12_color_warnings() {
  [[ -f "$LIMINE_CONF" ]] || return 0

  awk '
    function trim(value) {
      sub(/^[[:space:]]+/, "", value)
      sub(/[[:space:]]+$/, "", value)
      return value
    }
    BEGIN {
      color_key["interface_branding_color"] = 1
      color_key["interface_branding_colour"] = 1
      color_key["interface_help_color"] = 1
      color_key["interface_help_colour"] = 1
      color_key["interface_help_color_bright"] = 1
      color_key["interface_help_colour_bright"] = 1
    }
    /^[[:space:]]*#/ || /^[[:space:]]*$/ { next }
    {
      line = trim($0)
      colon = index(line, ":")
      if (colon == 0) next

      key = tolower(substr(line, 1, colon - 1))
      value = trim(substr(line, colon + 1))

      if ((key in color_key) && value !~ /^[0-9A-Fa-f]{6}$/) {
        print NR ": " key ": " value
      }
    }
  ' "$LIMINE_CONF"
}

list_unmanaged_windows_chainloads() {
  [[ -f "$LIMINE_CONF" ]] || return 0

  awk '
    function normalise_protocol(value) {
      value = tolower(value)
      if (value == "uefi" || value == "efi_chainload") return "efi"
      return value
    }

    function trim(value) {
      sub(/^[[:space:]]+/, "", value)
      sub(/[[:space:]]+$/, "", value)
      return value
    }
    /^[[:space:]]*#/ || /^[[:space:]]*$/ { next }
    {
      line = trim($0)
      # Limine strips leading whitespace, so entry lines ("/Name", "//Sub")
      # generated by limine-entry-tool/limine-snapper-sync may be indented.
      if (line ~ /^\//) { in_windows = (tolower(line) ~ /windows/); next }
      if (!in_windows) next
      colon = index(line, ":")
      if (colon == 0) next

      key = tolower(substr(line, 1, colon - 1))
      value = normalise_protocol(trim(substr(line, colon + 1)))
      if (key == "protocol" && value == "efi") {
        print NR ": " line
      }
    }
  ' "$LIMINE_CONF"
}

list_windows_firmware_entries() {
  command -v efibootmgr >/dev/null 2>&1 || return 0
  efibootmgr -v 2>/dev/null | grep -i 'bootmgfw\.efi' || true
}

list_omarchy_direct_boot_entries() {
  command -v efibootmgr >/dev/null 2>&1 || return 0
  efibootmgr -v 2>/dev/null | grep -Ei '^Boot[0-9A-Fa-f]+\*?[[:space:]]+Omarchy.*\\EFI\\Linux\\omarchy.*\.efi' || true
}

count_nonempty_lines() {
  local count=0 line
  while IFS= read -r line; do
    [[ -z "$line" ]] || count=$((count + 1))
  done <<< "$1"
  printf '%s\n' "$count"
}

show_status() {
  header "Secure Boot Status"
  local all_ok=true

  # Parse sbctl status
  local json secure_boot_state="" setup_mode_state="" installed_state=""
  json=$(sbctl status --json 2>/dev/null) || true

  if [[ -z "$json" || "$json" == "null" ]]; then
    # Fallback to raw output
    sbctl status
    echo
  else
    local vendors
    read -r installed_state setup_mode_state secure_boot_state < <(
      echo "$json" | jq -r '[.installed, .setup_mode, .secure_boot] | map(. // false) | @tsv'
    )
    vendors=$(echo "$json" | jq -r '
      .vendors // [] | if type == "array" then
        map(tostring) | sort | unique | join(", ")
      else
        tostring
      end
    ')

    if [[ "$installed_state" == "true" ]]; then
      pass "sbctl keys installed"
    else
      fail "sbctl keys not installed"
      all_ok=false
    fi

    if [[ "$secure_boot_state" == "true" ]]; then
      pass "Secure Boot enabled"
    else
      fail "Secure Boot disabled"
      all_ok=false
    fi

    if [[ "$setup_mode_state" == "true" ]]; then
      warn "Setup Mode active"
    else
      pass "Setup Mode disabled"
    fi
    [[ -n "$vendors" && "$vendors" != "null" ]] && echo -e "  ${DIM}Vendor keys: ${vendors}${NC}"
  fi

  # Hook status
  echo
  if [[ -f /etc/pacman.d/hooks/00-omasecboot-transition-guard.hook ]]; then
    pass "00-omasecboot-transition-guard.hook present (transaction guard)"
  else
    warn "00-omasecboot-transition-guard.hook missing. Run: ${BOLD}sudo make install${NC} from repo"
    [[ ${_lifecycle_state:-unmanaged} != active ]] || all_ok=false
  fi

  if [[ -f /etc/pacman.d/hooks/zz-omasecboot-cleanup.hook ]]; then
    pass "zz-omasecboot-cleanup.hook present (pre-sbctl lifecycle checkpoint)"
  else
    warn "zz-omasecboot-cleanup.hook missing. Run: ${BOLD}sudo make install${NC} from repo"
    [[ ${_lifecycle_state:-unmanaged} != active ]] || all_ok=false
  fi

  if [[ -f /usr/share/libalpm/hooks/zz-sbctl.hook ]]; then
    pass "zz-sbctl.hook present (re-signing)"
  else
    warn "zz-sbctl.hook missing. Run: ${BOLD}sudo pacman -S sbctl${NC}"
    [[ ${_lifecycle_state:-unmanaged} != active ]] || all_ok=false
  fi

  if [[ -f /etc/pacman.d/hooks/zzz-omasecboot.hook ]]; then
    pass "zzz-omasecboot.hook present (post-sbctl lifecycle checkpoint)"
  else
    warn "zzz-omasecboot.hook missing. Run: ${BOLD}sudo make install${NC} from repo"
    [[ ${_lifecycle_state:-unmanaged} != active ]] || all_ok=false
  fi

  if [[ -x /etc/boot/hooks/pre.d/000-omasecboot-guard ]]; then
    pass "000-omasecboot-guard present (Limine pre-mutation guard)"
  else
    warn "000-omasecboot-guard missing. Run: ${BOLD}sudo make install${NC} from repo"
    [[ ${_lifecycle_state:-unmanaged} != active ]] || all_ok=false
  fi

  if [[ -x /etc/boot/hooks/post.d/zzz-omasecboot-sign ]]; then
    pass "zzz-omasecboot-sign present (Limine post-mutation checkpoint)"
  else
    warn "zzz-omasecboot-sign missing. Run: ${BOLD}sudo make install${NC} from repo"
    [[ ${_lifecycle_state:-unmanaged} != active ]] || all_ok=false
  fi

  if command -v systemctl >/dev/null 2>&1; then
    local load_state enabled_state active_state
    load_state=$(systemctl show -p LoadState --value limine-snapper-sync.service 2>/dev/null || true)
    if [[ "$load_state" == "loaded" ]]; then
      enabled_state=$(systemctl is-enabled limine-snapper-sync.service 2>/dev/null || true)
      active_state=$(systemctl is-active limine-snapper-sync.service 2>/dev/null || true)

      if [[ "$enabled_state" == "enabled" ]]; then
        pass "limine-snapper-sync.service enabled"
      else
        warn "limine-snapper-sync.service not enabled (${enabled_state:-unknown})"
      fi

      if [[ "$active_state" == "active" ]]; then
        pass "limine-snapper-sync.service active"
      else
        warn "limine-snapper-sync.service not active (${active_state:-unknown})"
        if ! command -v inotifywait >/dev/null 2>&1; then
          echo -e "  ${DIM}limine-snapper-sync's optional file watcher requires ${BOLD}inotify-tools${NC}${DIM} (not needed by this repo's Limine post-hook)${NC}"
        fi
      fi
    fi
  fi

  echo
  echo -e "  ${BOLD}ESP Mount${NC}"
  if command -v mountpoint >/dev/null 2>&1 && command -v findmnt >/dev/null 2>&1; then
    local esp_fstype=""
    esp_fstype=$(findmnt -n -T "$ESP" -o FSTYPE 2>/dev/null) || esp_fstype=""
    if mountpoint -q "$ESP" && [[ "$esp_fstype" == "vfat" ]]; then
      pass "${ESP} mounted as vfat"
    else
      fail "${ESP} is not mounted as the FAT32 ESP (${esp_fstype:-not mounted})"
      all_ok=false
    fi
  else
    warn "mountpoint/findmnt unavailable; cannot verify ${ESP} mount"
  fi

  echo
  echo -e "  ${BOLD}Limine Config${NC}"
  if [[ -f /etc/default/limine ]]; then
    local enable_verification enable_verification_count
    load_limine_default_entry "ENABLE_VERIFICATION"
    enable_verification=$(strip_outer_quotes "${_limine_default_raw:-}")
    enable_verification_count=${_limine_default_count:-0}
    if [[ "$enable_verification" == "no" ]]; then
      pass "ENABLE_VERIFICATION=no"
    else
      fail "ENABLE_VERIFICATION is not set to no"
      all_ok=false
    fi
    if [[ $enable_verification_count -gt 1 ]]; then
      warn "ENABLE_VERIFICATION appears multiple times; sign will collapse it to one effective value"
    fi

    local enable_enroll enable_enroll_count
    load_limine_default_entry "ENABLE_ENROLL_LIMINE_CONFIG"
    enable_enroll=$(strip_outer_quotes "${_limine_default_raw:-}")
    enable_enroll_count=${_limine_default_count:-0}
    if [[ "$enable_enroll" == "yes" ]]; then
      pass "ENABLE_ENROLL_LIMINE_CONFIG=yes"
    else
      fail "ENABLE_ENROLL_LIMINE_CONFIG is missing"
      all_ok=false
    fi
    if [[ $enable_enroll_count -gt 1 ]]; then
      warn "ENABLE_ENROLL_LIMINE_CONFIG appears multiple times; sign will collapse it to one effective value"
    fi

    if limine_enrollment_hooks_present; then
      pass "Limine enrollment hooks present"
      if limine_default_has_command "COMMANDS_BEFORE_SAVE" "limine-reset-enroll" \
        || limine_default_has_command "COMMANDS_AFTER_SAVE" "limine-enroll-config"; then
        warn "deprecated COMMANDS_* enrollment entries remain; automatic cleanup is blocked until recovery is available"
      fi
    else
      warn "Limine enrollment hooks missing; checking deprecated COMMANDS_* fallback"
      if limine_default_has_command "COMMANDS_BEFORE_SAVE" "limine-reset-enroll"; then
        pass "COMMANDS_BEFORE_SAVE includes limine-reset-enroll"
      else
        fail "COMMANDS_BEFORE_SAVE is missing limine-reset-enroll fallback"
        all_ok=false
      fi

      if limine_default_has_command "COMMANDS_AFTER_SAVE" "limine-enroll-config"; then
        pass "COMMANDS_AFTER_SAVE includes limine-enroll-config"
      else
        fail "COMMANDS_AFTER_SAVE is missing limine-enroll-config fallback"
        all_ok=false
      fi
    fi

    local limine_major="" limine_ver=""
    limine_ver=$(limine_version 2>/dev/null || true)
    limine_major=$(limine_major_version 2>/dev/null || true)
    if [[ -n "$limine_ver" ]]; then
      pass "Limine ${limine_ver} installed"
    fi

    local color_warnings unhashed_paths limine_v12_or_newer=false
    if [[ -n "$limine_major" && $limine_major -ge 12 ]]; then
      limine_v12_or_newer=true
    fi

    color_warnings=$(list_limine_v12_color_warnings)
    if [[ -n "$color_warnings" ]]; then
      warn "Limine 12 expects interface colors as RRGGBB values"
      while IFS= read -r line; do
        echo -e "    ${YELLOW}!${NC} ${LIMINE_CONF}:${line}"
      done <<< "$color_warnings"
    fi

    if [[ "$enable_enroll" == "yes" ]]; then
      unhashed_paths=$(list_limine_unhashed_paths)
      if [[ -n "$unhashed_paths" ]]; then
        if [[ "$limine_v12_or_newer" == true && "$secure_boot_state" == "true" ]]; then
          fail "Limine 12 Secure Boot path-hash enforcement may block boot"
          while IFS= read -r line; do
            echo -e "    ${RED}✗${NC} ${LIMINE_CONF}:${line}"
          done <<< "$unhashed_paths"
          all_ok=false
        else
          warn "Limine 12 readiness: non-EFI loaded paths are missing BLAKE2B hashes"
          while IFS= read -r line; do
            echo -e "    ${YELLOW}!${NC} ${LIMINE_CONF}:${line}"
          done <<< "$unhashed_paths"
        fi
      else
        pass "Limine 12 path-hash readiness passed for non-EFI loaded paths"
      fi
    else
      echo -e "  ${DIM}Limine 12 path-hash enforcement inactive unless config enrollment is active${NC}"
    fi
  else
    fail "/etc/default/limine not found"
    all_ok=false
  fi

  local shadow_config shadow_config_found=false current_config_checksum
  while IFS= read -r shadow_config; do
    if [[ -e "$shadow_config" || -L "$shadow_config" ]]; then
      fail "Possible Limine config shadowing file: ${shadow_config}"
      shadow_config_found=true
      all_ok=false
    fi
  done < <(limine_shadow_config_paths)

  if [[ "$shadow_config_found" == false ]] \
    && current_config_checksum=$(current_limine_config_checksum) \
    && verify_limine_config_targets "$current_config_checksum"; then
    pass "Current Limine config checksum enrolled in both boot binaries"
  else
    [[ "$shadow_config_found" == true ]] \
      || fail "Current Limine config checksum is not proved in both boot binaries"
    all_ok=false
  fi

  local direct_boot_entries
  direct_boot_entries=$(list_omarchy_direct_boot_entries)
  if [[ -n "$direct_boot_entries" ]]; then
    warn "Omarchy Direct Boot firmware entry enabled"
    while IFS= read -r line; do
      echo -e "    ${YELLOW}!${NC} ${line}"
    done <<< "$direct_boot_entries"
    echo -e "  ${DIM}Direct Boot bypasses the Limine menu, including snapshots and repo-managed Windows entries.${NC}"
  fi

  # Windows boot path
  local windows_boot_entries windows_boot_count
  windows_boot_entries=$(list_windows_firmware_entries)
  windows_boot_count=$(count_nonempty_lines "$windows_boot_entries")
  if [[ $windows_boot_count -gt 0 ]]; then
    pass "Windows Boot Manager in firmware boot entries"
    if [[ $windows_boot_count -gt 1 ]]; then
      warn "Multiple Windows Boot Manager firmware entries found"
      while IFS= read -r line; do
        echo -e "    ${YELLOW}!${NC} ${line}"
      done <<< "$windows_boot_entries"
    fi
  else
    echo -e "  ${DIM}No Windows Boot Manager found (check BIOS boot settings)${NC}"
  fi

  if grep -Fq "$WINDOWS_ENTRY_MARKER" "$LIMINE_CONF" 2>/dev/null; then
    if grep -F -A4 "$WINDOWS_ENTRY_MARKER" "$LIMINE_CONF" | grep -q "protocol: efi_boot_entry"; then
      pass "Windows boot entry in limine.conf (firmware BootNext)"
    else
      warn "Managed Windows entry in limine.conf needs repair"
      echo -e "  ${DIM}Windows entry mutation is blocked until firmware target identity can be proven${NC}"
    fi
  else
    if [[ -f "${STATE_DIR}/windows-enabled" ]]; then
      echo -e "  ${DIM}Managed Windows entry is missing; repair awaits validated firmware target identity${NC}"
    else
      echo -e "  ${DIM}No Windows entry (run ${BOLD}sudo omasecboot windows setup${NC}${DIM} to add)${NC}"
    fi
  fi

  local unmanaged_windows_chainloads
  unmanaged_windows_chainloads=$(list_unmanaged_windows_chainloads)
  if [[ -n "$unmanaged_windows_chainloads" ]]; then
    warn "Windows EFI chainload entry may trigger BitLocker"
    while IFS= read -r line; do
      echo -e "    ${YELLOW}!${NC} ${LIMINE_CONF}:${line}"
    done <<< "$unmanaged_windows_chainloads"
    echo -e "  ${DIM}Omarchy Quattro's limine-scan creates this protocol: efi form.${NC}"
    echo -e "  ${DIM}OmaSecBoot uses firmware BootNext to keep Limine out of the Windows measurement chain.${NC}"
    echo -e "  ${DIM}Run ${BOLD}sudo omasecboot windows setup${NC}${DIM}, then remove any duplicate chainload entry if needed.${NC}"
  fi

  # Tracked files (root only)
  if [[ $EUID -eq 0 ]]; then
    echo
    echo -e "  ${BOLD}Tracked Files${NC}"
    local -a enrolled=()
    local -a discovered
    local -a untracked=()
    local file is_signed
    local enrolled_raw enrolled_rc=0
    local stale_entries stale_rc=0 stale_file stale_output
    declare -A enrolled_map=()
    local -a missing_tracked=()
    # Scoped to this section so the closing summary reflects file state
    # only, not unrelated failures (e.g. Secure Boot disabled).
    local files_ok=true

    enrolled_raw=$(list_enrolled_paths) || enrolled_rc=$?
    stale_entries=$(list_stale_sbctl_entries) || stale_rc=$?
    mapfile -t discovered < <(discover_efi_files)

    if [[ $stale_rc -eq 0 && -n "$stale_entries" ]]; then
      while IFS=$'\t' read -r stale_file stale_output; do
        stale_output="${stale_output:-$stale_file}"
        if [[ ! -e "$stale_file" || ! -e "$stale_output" ]]; then
          if [[ "$stale_file" == "$stale_output" ]]; then
            missing_tracked+=("$stale_file")
          else
            missing_tracked+=("$stale_file -> $stale_output")
          fi
        fi
      done <<< "$stale_entries"
    fi

    if [[ $enrolled_rc -ne 0 ]]; then
      fail "Could not read sbctl tracking state"
      all_ok=false
      files_ok=false
    elif [[ -n "$enrolled_raw" ]]; then
      mapfile -t enrolled <<< "$enrolled_raw"
    fi

    if [[ $enrolled_rc -ne 0 ]]; then
      : # already reported above
    elif [[ ${#enrolled[@]} -eq 0 ]]; then
      warn "No files in sbctl database"
      [[ ${#discovered[@]} -eq 0 ]] || { all_ok=false; files_ok=false; }
    else
      for file in "${enrolled[@]}"; do
        enrolled_map["$file"]=1
      done

      for file in "${discovered[@]}"; do
        if [[ -z "${enrolled_map[$file]:-}" ]]; then
          untracked+=("$file")
        fi
      done

      for file in "${enrolled[@]}"; do
        # sbctl verify exits 0 regardless of result; parse JSON for actual status
        is_signed=$(sbctl verify --json "$file" 2>/dev/null \
          | jq -r '.[0].is_signed // empty') || true
        if [[ "$is_signed" == "1" ]]; then
          echo -e "    ${GREEN}✓${NC} $file"
        else
          echo -e "    ${RED}✗${NC} $file"
          all_ok=false
          files_ok=false
        fi
      done

      if [[ ${#untracked[@]} -gt 0 ]]; then
        echo
        warn "Untracked EFI files found (${#untracked[@]})"
        for file in "${untracked[@]}"; do
          echo -e "    ${YELLOW}!${NC} $file"
        done
        if printf '%s\n' "${untracked[@]}" | grep -Eq '\.efi_(sha1|sha256|b3|blake3|xxh|xxhash)_'; then
          echo -e "  ${DIM}Snapshot UKIs exist outside sbctl's database. Repair is blocked until recovery is available; do not reboot with unresolved files.${NC}"
        fi
        all_ok=false
        files_ok=false
      fi

    fi

    if [[ $enrolled_rc -eq 0 && ${#missing_tracked[@]} -gt 0 ]]; then
      echo
      warn "Stale sbctl tracked files found"
      for stale_file in "${missing_tracked[@]}"; do
        echo -e "    ${YELLOW}!${NC} $stale_file"
      done
      echo -e "  ${DIM}Tracking repair is blocked until recovery is available; boot-mutating package transactions remain unavailable.${NC}"
      all_ok=false
      files_ok=false
    fi

    if [[ $enrolled_rc -eq 0 && ${#enrolled[@]} -gt 0 ]]; then
      echo
      if $files_ok; then
        pass "All tracked files signed and all discovered EFI files enrolled"
      else
        warn "Some files failed. Repair is blocked until recovery is available"
      fi
    fi
  else
    echo
    echo -e "  ${DIM}Run as root for file verification: ${BOLD}sudo omasecboot status${NC}"
  fi
  echo

  [[ "$all_ok" == true ]]
}
